### ISSUE TITLE
Include devDependencies 

### ISSUE THREAD

**Issue by MerlinMason** [nodeshift/license-reporter#339]
**Describe the bug**
By default only `dependencies` are included in the report. Running `license-reporter report --help` suggests you can pass options to change this `--include-dev-dependencies` or `--idd`. However these options do not do anything.

**To Reproduce**
Run `license-reporter report --idd` or `license-reporter report --idd=true` - only dependencies are included

**Expected behavior**
devDependencies should be included.

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.5
 - Node.js version: 12.3.1

**Comment by helio-frota** [comment]
@MerlinMason Thanks for report, I'll review to see what happened. But feel free to send a PR if you want to contribute. :+1:

**Comment by helio-frota** [comment]
@MerlinMason Hi, 

After investigate what happened in the past I guess I remembered and understood what happened.
The focus is production dependencies only, for example if we intend to package/ship a product only the `dependencies` will show on the report/output, not the `devDependencies`

This Issue here: https://github.com/nodeshift/license-reporter/issues/241 was to avoid the code search the `devDependencies` since we are **not** working/handling but still scanning/searching that time.

I think the best approach for now is to remove the `--idd` option from the command line to avoid more confusion. :+1:

**Comment by MerlinMason** [comment]
Ok, thanks for the update.
